package com.food.model;

/**
 * TPingjia generated by MyEclipse Persistence Tools
 */

public class TPingjia implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String content;

	private String shijian;

	private Integer productId;

	private Integer userId;
	private Integer haoping;

	private Integer zhongping;
	private Integer chaping;

	private String del;

	// Constructors

	/** default constructor */
	public TPingjia()
	{
	}

	/** full constructor */

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getContent()
	{
		return this.content;
	}

	public void setContent(String content)
	{
		this.content = content;
	}

	public String getShijian()
	{
		return this.shijian;
	}

	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}


	public Integer getproductId()
	{
		return productId;
	}

	public void setproductId(Integer productId)
	{
		this.productId = productId;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

	public Integer getHaoping() {
		return haoping;
	}

	public void setHaoping(Integer haoping) {
		this.haoping = haoping;
	}

	public Integer getZhongping() {
		return zhongping;
	}

	public void setZhongping(Integer zhongping) {
		this.zhongping = zhongping;
	}

	public Integer getChaping() {
		return chaping;
	}

	public void setChaping(Integer chaping) {
		this.chaping = chaping;
	}

}