package com.food.model;

import java.util.List;

/**
 * TProduct generated by MyEclipse Persistence Tools
 */

public class TProduct implements java.io.Serializable
{

	// Fields

	private Integer productId;

	private String productName;

	private String productMiaoshu;

	private String productPic;

	private String productYanse;

	private Integer productShichangjia;

	private Integer productTejia;

	private String productIsnottejia;

	private String productIsnottuijian;

	private Integer productCatelogId;
	
	private int productKucun;
	
	private String productDel;
	//new edit
	private String productShrq;
	
	private String productCatelogName;//���ݿ��û�У��Լ���ӵ�
	
	private Integer producthaoping;
	private Integer productzhongping;
	private Integer productchaping;
	
	private List pingjiaList;
	// Constructors

	/** default constructor */
	public TProduct()
	{
	}

	/** full constructor */
	public TProduct(String productName, String productMiaoshu, String productPic,
			String productYanse, Integer productShichangjia, Integer productTejia,
			String productIsnottejia, String productIsnottuijian,
			Integer productCatelogId,String productShrq)
	{
		this.productName = productName;
		this.productMiaoshu = productMiaoshu;
		this.productPic = productPic;
		this.productYanse = productYanse;
		this.productShichangjia = productShichangjia;
		this.productTejia = productTejia;
		this.productIsnottejia = productIsnottejia;
		this.productIsnottuijian = productIsnottuijian;
		this.productCatelogId = productCatelogId;
		this.productShrq=productShrq;
	}

	// Property accessors

	public Integer getproductId()
	{
		return this.productId;
	}

	public String getproductDel()
	{
		return productDel;
	}
	public List getPingjiaList()
	{
		return pingjiaList;
	}
	
	public void setPingjiaList(List pingjiaList)
	{
		this.pingjiaList = pingjiaList;
	}

	public int getproductKucun()
	{
		return productKucun;
	}

	public void setproductKucun(int productKucun)
	{
		this.productKucun = productKucun;
	}

	public void setproductDel(String productDel)
	{
		this.productDel = productDel;
	}

	public void setproductId(Integer productId)
	{
		this.productId = productId;
	}

	public String getproductName()
	{
		return this.productName;
	}

	public void setproductName(String productName)
	{
		this.productName = productName;
	}

	public String getproductMiaoshu()
	{
		return this.productMiaoshu;
	}

	public void setproductMiaoshu(String productMiaoshu)
	{
		this.productMiaoshu = productMiaoshu;
	}

	public String getproductPic()
	{
		return this.productPic;
	}

	public void setproductPic(String productPic)
	{
		this.productPic = productPic;
	}

	public String getproductYanse()
	{
		return this.productYanse;
	}

	public void setproductYanse(String productYanse)
	{
		this.productYanse = productYanse;
	}

	public Integer getproductShichangjia()
	{
		return this.productShichangjia;
	}

	public void setproductShichangjia(Integer productShichangjia)
	{
		this.productShichangjia = productShichangjia;
	}

	public Integer getproductTejia()
	{
		return this.productTejia;
	}

	public void setproductTejia(Integer productTejia)
	{
		this.productTejia = productTejia;
	}

	public String getproductIsnottejia()
	{
		return this.productIsnottejia;
	}

	public void setproductIsnottejia(String productIsnottejia)
	{
		this.productIsnottejia = productIsnottejia;
	}

	public String getproductIsnottuijian()
	{
		return this.productIsnottuijian;
	}

	public void setproductIsnottuijian(String productIsnottuijian)
	{
		this.productIsnottuijian = productIsnottuijian;
	}

	public Integer getproductCatelogId()
	{
		return this.productCatelogId;
	}

	public void setproductCatelogId(Integer productCatelogId)
	{
		this.productCatelogId = productCatelogId;
	}

	public String getproductCatelogName()
	{
		return productCatelogName;
	}

	public void setproductCatelogName(String productCatelogName)
	{
		this.productCatelogName = productCatelogName;
	}
	//new edit
	public void setproductShrq(String productShrq)
	{
		this.productShrq= productShrq;
	}

	public String getproductShrq()
	{
		return this.productShrq;
	}

	public Integer getproducthaoping() {
		return producthaoping;
	}

	public void setproducthaoping(Integer producthaoping) {
		this.producthaoping = producthaoping;
	}

	public Integer getproductzhongping() {
		return productzhongping;
	}

	public void setproductzhongping(Integer productzhongping) {
		this.productzhongping = productzhongping;
	}

	public Integer getproductchaping() {
		return productchaping;
	}

	public void setproductchaping(Integer productchaping) {
		this.productchaping = productchaping;
	}

}